---
title: "DATA 621 Homework 1"
author: "Alejandro D. Osborne"
date: "October 1, 2018"
output:
  html_document:
    df_print: paged
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressMessages(suppressWarnings(library(prettydoc)))
suppressMessages(suppressWarnings(library(psych)))
suppressMessages(suppressWarnings(library(knitr)))
suppressMessages(suppressWarnings(library(corrplot)))
suppressMessages(suppressWarnings(library(missForest)))
suppressMessages(suppressWarnings(library(data.table)))
suppressMessages(suppressWarnings(library(mltools)))
suppressMessages(suppressWarnings(library(htmlTable)))
suppressMessages(suppressWarnings(library(broom)))
suppressMessages(suppressWarnings(library(MLmetrics)))
suppressMessages(suppressWarnings(library(tidyverse)))
suppressMessages(suppressWarnings(library(ggthemes)))
suppressMessages(suppressWarnings(library(dplyr)))
library(dplyr)
suppressMessages(suppressWarnings(library(Hmisc)))
```


```{r}
train_raw <- read.csv("https://raw.githubusercontent.com/AlejandroOsborne/DATA-621/master/moneyball-training-data.csv")
test_raw <- dplyr::select(read.csv("https://raw.githubusercontent.com/AlejandroOsborne/DATA-621/master/moneyball-evaluation-data.csv"), - INDEX)
```


```{r}
set.seed(5)
```

```{r}
metadata <- function(df){
  #Takes a data frame & Checks NAs, class types, inspects the unique values
  df_len <- nrow(df)
  NA_ct = as.vector(rapply(df, function(x) sum(is.na(x))))
    #create dataframe  
  df_metadata <- data.frame(
    vars = names(df),
    class_type = rapply(lapply(df, class), function(x) x[[1]]),
    n_rows = rapply(df, length),
    complete_cases = sum(complete.cases(df)),
    NA_ct = NA_ct,
    NA_pct = NA_ct / df_len * 100,
    unique_value_ct = rapply(df, function(x) length(unique(x))),
    most_common_values = rapply(df, function(x) str_replace(paste(names(sort(summary(as.factor(x)), decreasing=T))[1:5], collapse = '; '), "\\(Other\\); ", ""))
  )
 rownames(df_metadata) <- NULL
 return(df_metadata)
}

meta_df <- metadata(train_raw)
```


```{r}
kable(meta_df, digits = 1) 
metrics <- function(df){
  ###Creates summary metrics table
  metrics_only <- df[, which(rapply(lapply(df, class), function(x) x[[1]]) %in% c("numeric", "integer"))]
  
  df_metrics <- psych::describe(metrics_only, quant = c(.25,.75))
  
  df_metrics <- 
    dplyr::select(df_metrics, n, min, Q.1st = Q0.25, median, mean, Q.3rd = Q0.75, 
    max, range, sd, se, skew, kurtosis
  )
  
  return(df_metrics)
}

metrics_df <- metrics(train_raw)
```

```{r}
kable(metrics_df, digits = 1, format.args = list(big.mark = ',', scientific = F, drop0trailing = T))
#calculate some parameters to deal with the outliers
train_stacked <- na.omit(stack(train_raw))
bpstats <- boxplot(values ~ ind, data = train_stacked, plot = F)$stats
ylimits <- c(0, ceiling(max(bpstats) / 200)) * 200
ybreaks <- seq(ylimits[1], ylimits[2], by = 200)
outliers_not_shown <- paste(sum(train_stacked$values > max(ylimits)), "outlier(s) not displayed") 
```

```{r}
ggplot(data = train_stacked, mapping = aes(x = ind, y = values)) + 
  geom_boxplot(outlier.size = 1) +
  labs(caption = paste("Red dot = mean", outliers_not_shown, sep = "\n")) +
  scale_x_discrete(limits = rev(levels(train_stacked$ind))) +
  scale_y_continuous(breaks = ybreaks) +
  stat_summary(fun.y=mean, geom="point", size=2, color = "red") +
  coord_flip(ylim = ylimits) +
  theme_fivethirtyeight()
```

```{r}
hist.data.frame(train_raw)
```



```{r}
cormatrix <- cor(drop_na(train_raw))
```

```{r}
cor_df <- data.frame(Var1=rownames(cormatrix)[row(cormatrix)],
                     Var2=colnames(cormatrix)[col(cormatrix)],
                     Correlation=c(cormatrix))

```

```{r}
corr_list <- 
  cor_df %>% 
  filter(Var1 != Var2) %>% 
  arrange(-Correlation)
```



```{r}
sort_rows <- t(apply(corr_list, 1, sort, decreasing = T))
fin_list <- corr_list[!duplicated(sort_rows), ]
rownames(fin_list) <- 1:nrow(fin_list)
#print table
kable(head(fin_list, 12), digits=4, row.names = T, caption = "Top 12 Correlated Variable Pairs")
```

```{r}
corrplot(cormatrix, method = "square", type = "upper")

train_raw$TEAM_PITCHING_H <- bin_data(train_raw$TEAM_PITCHING_H, bins = 5, binType = "quantile") 

levels(train_raw$TEAM_PITCHING_H) <- c("One","Two","Three","Four","Five")

impute_missing <- missForest(train_raw, variablewise = T)
```

```{r}
impute_df <- cbind(meta_df, 
                   range = metrics_df$range,
                   MSE = as.numeric(impute_missing$OOBerror),
                   variable = names(impute_missing$ximp)) %>% 
  select(variable, NA_ct, NA_pct, MSE) %>% 
  mutate(RMSE = sqrt(as.numeric(impute_missing$OOBerror)),
         NRMSE = sqrt(as.numeric(impute_missing$OOBerror))/metrics_df$range) %>% 
  filter(MSE > 0) %>% 
  arrange(-NRMSE)
```



```{r}
kable(impute_df, digits = 2) 
train_raw_less_one <- select(train_raw, -TEAM_BATTING_HBP)
impute_missing <- missForest(train_raw_less_one, variablewise = T)
```


```{r}
impute_df <- cbind(metadata(train_raw_less_one), 
                   range = rapply(impute_missing$ximp, max) - rapply(impute_missing$ximp, min),
                   MSE = as.numeric(impute_missing$OOBerror),
                   variable = names(impute_missing$ximp)) %>% 
  select(variable, NA_ct, NA_pct, MSE) %>% 
  mutate(RMSE = sqrt(as.numeric(impute_missing$OOBerror)),
         NRMSE = sqrt(as.numeric(impute_missing$OOBerror))/(rapply(impute_missing$ximp, max) - rapply(impute_missing$ximp, min))) %>% 
  filter(MSE > 0) %>% 
  arrange(-NRMSE)
```


```{r}
kable(impute_df, digits = 2)

train_imputed <- impute_missing$ximp 
class(train_imputed$TEAM_PITCHING_H) <- "factor"

mod1 <- lm(TARGET_WINS ~ ., data = train_imputed)

```


```{r}
summary(mod1) 
summary(aov(TARGET_WINS~TEAM_PITCHING_H, data = train_imputed))
filter(fin_list, Var2 == "TARGET_WINS")[1:4,]

mod2 <- lm(TARGET_WINS ~ TEAM_PITCHING_H + TEAM_BATTING_H + TEAM_BATTING_BB + TEAM_PITCHING_BB, data = train_imputed)

summary(mod2)

mod3 <- update(mod1, .~. -TEAM_FIELDING_DP -TEAM_BATTING_2B -TEAM_BASERUN_CS -TEAM_PITCHING_HR, data = train_imputed)
#summary(mod3) #R
```


```{r}
#remove TEAM_PITCHING_BB at 0.598258 
mod3 <- update(mod3, .~. -TEAM_PITCHING_BB, data = train_imputed)
#summary(mod3) #new R-sq = 0.3342

#remove TEAM_BATTING_BB at 0.169551
mod3 <- update(mod3, .~. -TEAM_BATTING_BB, data = train_imputed)
#summary(mod3) #new R-sq = 0.3341

#remove TEAM_PITCHING_H  
mod3 <- update(mod3, .~. -TEAM_PITCHING_H, data = train_imputed)
#summary(mod3) #new R-sq = 0.3284

#remove TEAM_PITCHING_SO, it appears collinear  
mod3 <- update(mod3, .~. -TEAM_PITCHING_SO, data = train_imputed)
#summary(mod3) #new R-sq = 0.3273

#remove TEAM_BATTING_3B,  
mod3 <- update(mod3, .~. -TEAM_BATTING_3B, data = train_imputed)
summary(mod3) #new R-sq = 0.3273
```


```{r}
PRESS <- function(linear.model) {
  #source:  https://gist.github.com/tomhopper/8c204d978c4a0cbcb8c0#file-press-r
  #' calculate the predictive residuals
  pr <- residuals(linear.model)/(1-lm.influence(linear.model)$hat)
  #' calculate the PRESS
  PRESS <- sum(pr^2)
  
  return(PRESS)
}
```


```{r}
pred_r_squared <- function(linear.model) {
  #source: https://gist.github.com/tomhopper/8c204d978c4a0cbcb8c0#file-pred_r_squared-r
  #' Use anova() to get the sum of squares for the linear model
  lm.anova <- anova(linear.model)
  #' Calculate the total sum of squares
  tss <- sum(lm.anova$'Sum Sq')
  # Calculate the predictive R^2
  pred.r.squared <- 1-PRESS(linear.model)/(tss)
  
  return(pred.r.squared)
}
```

```{r}
model_summary <- function(model, y_var) {
    ### Summarizes the model's key statistics in one row
    df_summary <- glance(summary(model))
    model_name <- deparse(substitute(model))
    n_predictors <- ncol(model$model) - 1
    pred.r.squared <- pred_r_squared(model)
    df_summary <- cbind(model_name, n_predictors, pred.r.squared, df_summary)
    return(df_summary)
}
```


```{r}
mod_sum_df1 <- model_summary(mod1, "TARGET_WINS")
mod_sum_df2 <- model_summary(mod2, "TARGET_WINS")
mod_sum_df3 <- model_summary(mod3, "TARGET_WINS")
```

```{r}
kable(all_results <- rbind(mod_sum_df1, mod_sum_df2, mod_sum_df3), digits = 4)
par(mfrow=c(2,2))
plot(mod3)
kable(metadata(test_raw), digits = 1)
```

```{r}
test_raw$TEAM_PITCHING_H <- bin_data(test_raw$TEAM_PITCHING_H, bins = 5, binType = "quantile") 

levels(test_raw$TEAM_PITCHING_H) <- c("One","Two","Three","Four","Five")

test_raw_less_one <- select(test_raw, -TEAM_BATTING_HBP)

impute_missing_test <- missForest(test_raw_less_one, variablewise = T)
 
# check imputation error
impute_df <- cbind(metadata(test_raw_less_one), 
                   range = rapply(impute_missing_test$ximp, max) - rapply(impute_missing_test$ximp, min),
                   MSE = as.numeric(impute_missing_test$OOBerror),
                   variable = names(impute_missing_test$ximp)
                   ) %>% 
  select(variable, NA_ct, NA_pct, MSE) %>% 
  mutate(RMSE = sqrt(as.numeric(impute_missing_test$OOBerror)),
         NRMSE = sqrt(as.numeric(impute_missing_test$OOBerror))/(rapply(impute_missing_test$ximp, max) - rapply(impute_missing_test$ximp, min))) %>% 
  filter(MSE > 0) %>% 
  arrange(-NRMSE)

kable(impute_df, digits = 2)

test_imputed <- impute_missing$ximp 
class(test_imputed$TEAM_PITCHING_H) <- "factor"
test_results <- predict(mod3, newdata = test_imputed)
```
